### ISSUE TITLE
Sub-menu support documentation

### ISSUE THREAD

**Issue by dg01d** [SteveEdson/bitbar-php#12]
Hi Steve,

Love the library, makes lines and dropdowns a breeze, but:

`As of v1.8.0, Bitbar supports sub menus.`

Could you explain _how_ it supports them? I can see that the logic in the file is ` public function addSubMenu()` but I can't get this to work in my scripts.

**Comment by SteveEdson** [comment]
Thanks!

No problem, i'll update the readme, but here's how it can be done:

```php
// Create BitBar formatter
$bb = new BitBar();

// Create the first line
$line = $bb->newLine();

// Set the text and formatting
$mainMenu = $line
    ->setText("Servers")
    ->setColour("yellow");

$mainMenu = $mainMenu->addSubMenu()
    ->newLine()
    ->setText("Server 1")
    ->setUrl('http://server1.com');

$mainMenu = $mainMenu->addSubMenu()
    ->newLine()
    ->setText("Server 2")
    ->setUrl('http://server2.com');

$mainMenu->show();
```

Thanks!
