### ISSUE TITLE
setFontFace — I see no changes?

### ISSUE THREAD

**Issue by gingerbeardman** [SteveEdson/bitbar-php#13]
using this:
```php
$line = $bb->newLine();
$line
    ->setText($scores)
    ->setFontFace("courier")
    ->setDropdown(true)
    ->show();
```
I do not see any changed font? plugin works fine otherwise.
https://github.com/dg01d/bitbar-plugins/blob/master/Sports/worldcup.1m.php

I have confirmed I can see courier using this plugin: 
https://github.com/matryer/bitbar-plugins/blob/master/Tutorial/ansi.sh

Any ideas?

**Comment by gingerbeardman** [comment]
If I manually add this to the string

` | font=courier trim=false` or ` | font="Courier New" trim=false`

I do see the Courier font.

But still no luck with
```
$line = $bb->newLine();
$line
    ->setText($scores)
    ->setFontFace("courier")
    ->disableTrim()
    ->setDropdown(true)
    ->show();
```

**Comment by SteveEdson** [comment]
Looking at the code, I seemed to have made it require a font size as a well as the font name for it to be displayed. Adding

```
    ->setFontFace("courier")
    ->setFontSize(14)
```

will fix the issue. I'll look into changing this.

Thanks

**Comment by gingerbeardman** [comment]
Still no luck even with those lines

Neither size nor face take effect :(

Using them also makes setColor stop working, where it does work without them?

**Comment by gingerbeardman** [comment]
A 2 year old PR split the font/size?

https://github.com/SteveEdson/bitbar-php/pull/8

**Comment by gingerbeardman** [comment]
OK, figured it out.

font value needs quoting, will send PR shortly.

**Comment by SteveEdson** [comment]
@gingerbeardman I've just pushed `0.4.2` which merges #8 and also quotes the values, can you try that please? (Might need to use the master branch if composer doesn't see the change yet).

Thanks

**Comment by gingerbeardman** [comment]
Snap! Same changes I had just made. Your file works a treat

thank you
